### ISSUE TITLE
代老师您好，我有一些参数估计相关的问题，在别处找不到您的电子邮箱地址，所以就在这提问了，冒昧打扰。

### ISSUE THREAD

**Issue by qipengchen** [inuyasha2012/vipsy#1]
老师你好，我是浙江师范大学一名学习心理计量学的研究生，最近在学习MCMC参数估计的实现。在网上搜集资料的过程中看到了您的文章，才发现变分推理也已经用于心理计量模型。

但是因为自己能力的原因，并不能直接使用这种变分推理的方式进行参数估计。想要先尝试传统的马尔可夫链抽样形式的参数估计。

如果只是传统的马尔可夫链抽样方式，能不能用pyro实现，如果能够实现，应该如何去做，如果有教程的链接就更感谢了。如果不能实现，有没有什么其他的python包推荐呢。

谢谢老师，祝老师天天开心！

**Comment by inuyasha2012** [comment]
inuyasha2010 我的微信

**Comment by qipengchen** [comment]
老师您好，这个微信号加不上，显示“该用户不存在”

**Comment by inuyasha2012** [comment]
不好意思，设置了不能通过微信号加，你再试试













在 2021-04-14 08:15:55，"qipengchen" ***@***.***> 写道：

老师您好，这个微信号加不上，显示“该用户不存在”
